using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using Accountant.Models;
using Accountant.Forms;

namespace Accountant
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Accountant.Models.AccountantDBEntities dbContext = new Accountant.Models.AccountantDBEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Transactions.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.Transactions.Local.ToBindingList();

            //LoadTransactions();
        }

        private void btnAddTransaction_Click(object sender, EventArgs e)
        {
            var addTransactionForm = new AddTransactionForm();
            addTransactionForm.ShowDialog();

            // Refresh the GridControl after adding a transaction
            LoadTransactions();
        }

        private void LoadTransactions()
        {
            using (var db = new AccountantDBEntities())
            {
                gridControl1.DataSource = db.Transactions.ToList();
            }
        }

        private void btnEditTransaction_Click(object sender, EventArgs e)
        {
            // Get the selected transaction
            var selectedTransaction = gridView1.GetFocusedRow() as Transaction;

            if (selectedTransaction == null)
            {
                MessageBox.Show("Please select a transaction to edit.", "No Selection", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            // Open the EditTransactionForm
            var editTransactionForm = new EditTransactionForm(selectedTransaction);
            editTransactionForm.ShowDialog();

            // Refresh the GridControl
            LoadTransactions();
        }

        private void btnDeleteTransaction_Click(object sender, EventArgs e)
        {
            // Get the selected transaction
            var selectedTransaction = gridView1.GetFocusedRow() as Transaction;

            if (selectedTransaction == null)
            {
                MessageBox.Show("Please select a transaction to delete.", "No Selection", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            var result = MessageBox.Show("Are you sure you want to delete this transaction?",
                                         "Confirm Delete", MessageBoxButtons.YesNo, MessageBoxIcon.Question);

            if (result == DialogResult.Yes)
            {
                try
                {
                    using (var db = new AccountantDBEntities())
                    {
                        var transaction = db.Transactions.Find(selectedTransaction.TransactionID);

                        if (transaction != null)
                        {
                            db.Transactions.Remove(transaction);
                            db.SaveChanges();
                        }
                    }

                    MessageBox.Show("Transaction deleted successfully.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    LoadTransactions();
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

    }
}
